"""add unit_price to line_items

Revision ID: 88234cb2d8e3
Revises: 7ed9f18e4bbe
Create Date: 2026-06-17 09:59:53.438305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88234cb2d8e3'
down_revision: Union[str, Sequence[str], None] = '7ed9f18e4bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
